package com.altaqwa.app

import android.annotation.SuppressLint
import android.os.Bundle
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import android.webkit.WebChromeClient
import android.view.View
import android.widget.ProgressBar
import androidx.appcompat.app.AppCompatActivity

/**
 * MainActivity - WebView-based App
 * 
 * Generated by AHteam Factory
 * 
 * Configuration:
 * - App Name: {{project.name}}
 * - Start URL: Configured below
 * - No external dependencies
 */
class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView
    private lateinit var progressBar: ProgressBar

    // Configuration - from project.config.json
    companion object {
        const val START_URL = "file:///android_asset/index.html"
        const val APP_NAME = "{{project.name}}"
    }

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // Initialize views
        webView = findViewById(R.id.webView)
        progressBar = findViewById(R.id.progressBar)

        // Configure WebView
        setupWebView()

        // Load content
        webView.loadUrl(START_URL)
    }

    private fun setupWebView() {
        webView.apply {
            // Enable JavaScript
            settings.javaScriptEnabled = true
            settings.domStorageEnabled = true
            settings.allowFileAccess = true
            settings.allowContentAccess = true
            
            // Cache settings
            settings.cacheMode = WebSettings.LOAD_DEFAULT
            
            // Enable zoom
            settings.builtInZoomControls = true
            settings.displayZoomControls = false
            settings.setSupportZoom(true)
            
            // Performance
            settings.loadWithOverviewMode = true
            settings.useWideViewPort = true
            
            // RTL Support
            settings.layoutAlgorithm = WebSettings.LayoutAlgorithm.TEXT_AUTOSIZING

            // WebView Client
            webViewClient = object : WebViewClient() {
                override fun onPageFinished(view: WebView?, url: String?) {
                    super.onPageFinished(view, url)
                    progressBar.visibility = View.GONE
                }

                override fun shouldOverrideUrlLoading(view: WebView?, url: String?): Boolean {
                    // Keep navigation within the app
                    url?.let { view?.loadUrl(it) }
                    return true
                }
            }

            // Chrome Client for progress
            webChromeClient = object : WebChromeClient() {
                override fun onProgressChanged(view: WebView?, newProgress: Int) {
                    progressBar.progress = newProgress
                    if (newProgress == 100) {
                        progressBar.visibility = View.GONE
                    } else {
                        progressBar.visibility = View.VISIBLE
                    }
                }
            }
        }
    }

    // Handle back button
    override fun onBackPressed() {
        if (webView.canGoBack()) {
            webView.goBack()
        } else {
            super.onBackPressed()
        }
    }
}
